version: "3.9"
services:
  app:
    container_name: app_container
    build:
      context: ./docker/app
      dockerfile: Dockerfile

  web:
    container_name: web_container
    build:
      context: ./docker/web
      dockerfile: Dockerfile
    ports:
      - 18080:80
    depends_on:
      - app # php-fpmをconfで実施しているため