FROM php:8.2-apache-bullseye

ENV TZ Asia/Tokyo

RUN apt-get update \
  && apt-get upgrade -y \
  && apt-get install -y --no-install-recommends \
    curl \
    vim \
    less source-highlight \
    mariadb-server \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
# xdebug
RUN pecl install xdebug \
  && docker-php-ext-enable xdebug
COPY xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini

# pdo
RUN docker-php-ext-install pdo_mysql


RUN service mariadb start
# apache modules
RUN a2enmod rewrite

# WORKDIR /etc/apache2/conf-available/
WORKDIR /var/www/html

# shellで、サービスを起動するように設定するべきか？
# ENTRYPOINT [ "mysql", "" ]
