FROM php:8.2-apache-bullseye

ENV TZ Asia/Tokyo

RUN apt-get update \
  && apt-get upgrade -y \
  && apt-get install -y --no-install-recommends \
    curl \
    vim \
    less source-highlight \
  && apt-get clean \
  # && rm -rf /var/lib/apt/lists* \
  #   && docker-php-ext-install \
  #       intl \
  #       bcmath \
  #       pdo \
  #       pdo_mysql &&\
  #   pecl install xdebug \
  #   && docker-php-ext-enable xdebug    

RUN a2enmod rewrite

# WORKDIR /etc/apache2/conf-available/
WORKDIR /var/www/html
