version: '3'
services:
  ubuntu:
    build:
      context: ./docker
      # dockerfile: Dockerfile
      dockerfile: Alma-Dockerfile
    # フォアグラウンドで実行させるタスクがないと、正常終了されてしまうため。
    hostname: ubuntu22
    container_name: ubuntu22
    tty: true
    # 127.0.0.1～127.255.255.254
    ports:
        # 0.0.1でなくてもアクセスできる
        # - 127.0.0.1:8082:80
        - 127.0.1.1:8082:80