up:
	docker compose up -d
dw:
	docker compose down
b:
	docker compose build
ncb:
	docker compose build --no-cache
prune:
	docker system prune -f
bash:
	docker compose exec ubuntu bash
l:
	docker compose logs
p:
	docker compose ps