FROM php:8.0-fpm

RUN apt update \
    && apt install -y  --no-install-recommends\
        git \
        unzip \
        vim \
        libicu-dev \
        libpq-dev \
        libzip-dev \
        zip \
        zlib1g-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists* \
    && docker-php-ext-install \
        intl \
        bcmath \
        pdo \
        pdo_mysql &&\
    pecl install xdebug \
    && docker-php-ext-enable xdebug

WORKDIR /var/www/my_app

COPY --from=composer:2.3.9 /usr/bin/composer /usr/bin/composer
# RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

COPY ./php.ini /usr/local/etc/php/php.ini

RUN mkdir -pm 777 /etc/php/session &&\
    echo -e "\n alias ll='ls -la --color'\n" >> /root/.bashrc