# Laravelの開発環境を作る
FROM php:8.0-fpm

ENV TZ Asia/Tokyo

RUN apt-get update && \ 
    # --no-install-recommends 必要な機能のみinstall 
    apt-get install -y  --no-install-recommends \
        vim \
        unzip \
        libicu-dev \
        libonig-dev \
        libzip-dev \
        git && \    
    apt-get clean && \
    docker-php-ext-enable xdebug && \
    docker-php-ext-install \
        pdo_mysql \
        intl \
        bcmath && \
        # PHP Extension Community Library
        pecl install xdebug

COPY ./php.ini /usr/local/etc/php/php.ini

# マルチステージビルドでcomposerインストール
# COPY --from=composer /usr/bin/composer /usr/bin/composer
COPY --from=composer:2.3.9 /usr/bin/composer /usr/bin/composer

# TODO 自動でプロジェクト作成まで持っていけないか？
ENV COMPOSER_ALLOW_SUPERUSER=1

WORKDIR /app

#######################
# 操作
#######################
# 単独実行
# docker build -t php-8.0:1.0 .
# docker run -itd php-8.0:1.0 imageID