version: "3.9"
services:
  app:
    container_name: ${APP_NAME}_app
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/public_html
      # laravel 高速化
      - /var/www/public_html/${APP_NAME}/storage/framework
      - /var/www/public_html/${APP_NAME}/vendor
    expose:
      - 9000
    depends_on:
      - db 

  web:
    container_name: ${APP_NAME}_web
    build:
      context: ./docker/web
      dockerfile: Dockerfile
    ports:
      - 18080:80
    depends_on:
      - app
    volumes:
      - ./src:/var/www/public_html
      - ./docker/web/logs:/var/log/nginx/ 

  db:
    container_name: ${APP_NAME}_db
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    volumes:
      - db_store:/var/lib/mysql
      - ./docker/db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 4306:3306

  mailhog:
    image: 
      mailhog/mailhog:latest
    container_name: ${APP_NAME}_mail
    ports:
      - 8025:8025
      - 1025:1025

volumes:
  db_store: