alias:
	alias sail=^'[ -f sail ] && bash sail || bash vendor/bin/sail^'

up:
	./vendor/bin/sail up -d

down:
	./vendor/bin/sail down

shell:
	./vendor/bin/sail shell

ps:
	./vendor/bin/sail ps

mysql:
	./vendor/bin/sail mysql

artisan:
	./vendor/bin/sail artisan

# @make up
# https://qiita.com/ucan-lab/items/56c9dc3cf2e6762672f4
