version: '3.8'
# baindマウントと、volumeマウントの違いを意識しよう
volumes:
  db-store:
services:
  db:
    image: mysql:8
    container_name: my_db
    # コンテナ停止時に再起動(手動停止を除く)
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=test_user
      - MYSQL_PASSWORD=test_password
    volumes:
      - db-store:/var/lib/mysql
      - ./docker/db/my.conf:/etc/mysql/conf.d/my.cnf
    ports:
      - 4306:3306

  app:
    container_name: my_app
    build:
      context: ./docker/app
      dockerfile: Dockerfile-app
    volumes:
      - ./src:/var/www/my_app
      - ./docker/app/log:/var/log
    depends_on:
      - db

  web:  
    container_name: my_web
    build:
      context: ./docker/web
      dockerfile: Dockerfile-web
    volumes:
      - ./src:/usr/share/nginx/html
    tty: true
    ports:
      - 18080:80
    depends_on:
      - app