FROM php:8.0-apache

RUN apt update && \
    apt install -y  --no-install-recommends\
        git \
        unzip \
        vim \
        libicu-dev \
        libpq-dev \
        libzip-dev \
        zip \
        zlib1g-dev && \
    apt-get clean && \
    docker-php-ext-install \
        intl \
        bcmath \
        pdo \
        pdo_mysql

WORKDIR /var/www/my_app

COPY --from=composer:2.3.9 /usr/bin/composer /usr/bin/composer
# RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer